---
feature : 
  phat : False
---
scheduler: # Plateau, oneCycle, CosineAnnealingLR
  type: "CosineAnnealingLR"
  oneCycle:
    max_lr: 0.0001
  Plateau:
    mode: 'min'
    patience: 2
    factor: 0.5
    min_lr: 0.000005
  CosineAnnealingLR : 
    T_max : 50  # Maximum number of iterations.
    eta_min : 0.000001